CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    email       VARCHAR(180) NOT NULL,
    phone       VARCHAR(20),
    password    VARCHAR(100) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(180),
    updated_by  VARCHAR(180),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE addresses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    cep           VARCHAR(8)   NOT NULL,
    street        VARCHAR(200) NOT NULL,
    number        VARCHAR(20)  NOT NULL,
    complement    VARCHAR(100),
    state         VARCHAR(2)   NOT NULL,
    city          VARCHAR(100) NOT NULL,
    district      VARCHAR(100),
    main_address  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    created_by    VARCHAR(180),
    updated_by    VARCHAR(180),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_addresses_user_id ON addresses (user_id);
CREATE INDEX idx_addresses_city ON addresses (city);